// <auto-generated />
using System;
using MVCDay2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCDay2.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20230121191844_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCDay2.Models.Department", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Number");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MVCDay2.Models.Dependent", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Emp_SSN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BDate")
                        .HasColumnType("Date");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name", "Emp_SSN");

                    b.HasIndex("Emp_SSN");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("MVCDay2.Models.Dept_loc", b =>
                {
                    b.Property<int>("Dept_id")
                        .HasColumnType("int");

                    b.Property<string>("Locatoin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Dept_id", "Locatoin");

                    b.ToTable("Dept_Locs");
                });

            modelBuilder.Entity("MVCDay2.Models.Emp_Proj", b =>
                {
                    b.Property<int>("Emp_SSN")
                        .HasColumnType("int");

                    b.Property<int>("Proj_Id")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("Emp_SSN", "Proj_Id");

                    b.HasIndex("Proj_Id");

                    b.ToTable("Emp_Projs");
                });

            modelBuilder.Entity("MVCDay2.Models.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BDate")
                        .HasColumnType("Date");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<int?>("Super_SSN")
                        .HasColumnType("int");

                    b.HasKey("SSN");

                    b.HasIndex("Super_SSN");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MVCDay2.Models.Project", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<int>("Dept_id")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Number");

                    b.HasIndex("Dept_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MVCDay2.Models.Dependent", b =>
                {
                    b.HasOne("MVCDay2.Models.Employee", "employee")
                        .WithMany("Dependents")
                        .HasForeignKey("Emp_SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("MVCDay2.Models.Dept_loc", b =>
                {
                    b.HasOne("MVCDay2.Models.Department", "department")
                        .WithMany("Dept_Locs")
                        .HasForeignKey("Dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("MVCDay2.Models.Emp_Proj", b =>
                {
                    b.HasOne("MVCDay2.Models.Employee", "employee")
                        .WithMany("Emp_Projs")
                        .HasForeignKey("Emp_SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCDay2.Models.Project", "project")
                        .WithMany("Emp_Projs")
                        .HasForeignKey("Proj_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("project");
                });

            modelBuilder.Entity("MVCDay2.Models.Employee", b =>
                {
                    b.HasOne("MVCDay2.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("Super_SSN");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("MVCDay2.Models.Project", b =>
                {
                    b.HasOne("MVCDay2.Models.Department", "department")
                        .WithMany("Projects")
                        .HasForeignKey("Dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("MVCDay2.Models.Department", b =>
                {
                    b.Navigation("Dept_Locs");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MVCDay2.Models.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Emp_Projs");
                });

            modelBuilder.Entity("MVCDay2.Models.Project", b =>
                {
                    b.Navigation("Emp_Projs");
                });
#pragma warning restore 612, 618
        }
    }
}
